services:
  toonka_adminer:
    image: adminer:latest
    restart: always
    container_name: toonka_adminer
    depends_on:
      toonka_db:
        condition: service_healthy
    ports:
      - 3001:8080
    environment:
      ADMINER_DEFAULT_SERVER: toonka_db

  toonka_db:
    image: postgres:latest
    restart: always
    container_name: toonka_db
    volumes:
      - toonka_db:/var/lib/postgresql/data
    ports:
      - 3002:5432
    environment:
      POSTGRES_DB: toonka
      POSTGRES_USER: toonka
      POSTGRES_PASSWORD: toonka
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  toonka_db:
